-- upgrade --
CREATE TABLE IF NOT EXISTS `pixel` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `x` INT NOT NULL,
    `y` INT NOT NULL,
    `color` VARCHAR(16) NOT NULL,
    `modify_times` INT NOT NULL  DEFAULT 0,
    `last_modify` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
